packages:
  - '.'

allowBuilds:
  '@astryxdesign/cli': true
  '@astryxdesign/core': true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@astryxdesign/core@0.6.6'
  - '@astryxdesign/lab@0.6.6-canary.dc3a939'
  - '@astryxdesign/richtext@0.6.6-canary.dc3a939'
  - '@astryxdesign/cli@0.6.6'
