/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/shared/components/theme.js
 * Command: astryx theme build src/shared/components/theme.js --out src/shared/components/theme.built.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * kt-xnk theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { ktXnkTheme } from './kt-xnk';
 *   import './kt-xnk.css';
 */
export const ktXnkTheme = {
  name: 'kt-xnk',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.375rem",
    "--font-size-2xs": "0.4375rem",
    "--font-size-xs": "0.5625rem",
    "--font-size-sm": "0.6875rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.6875rem",
    "--font-size-3xl": "2.125rem",
    "--font-size-4xl": "2.6875rem",
    "--font-size-5xl": "3.3125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.4545",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.7778",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "12px",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4545",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.283",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2093",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2941",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "\"Optimistic Text Vietnamese\", \"Optimistic Text\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "var(--font-montserrat), \"Figtree\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "var(--font-jetbrains-mono), \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#645a72, #b2a7c1)",
    "--color-syntax-string": "light-dark(#4e6357, #9bb19a)",
    "--color-syntax-comment": "light-dark(#5e5e5e, #ababb0)",
    "--color-syntax-number": "light-dark(#755752, #bea792)",
    "--color-syntax-function": "light-dark(#506072, #99adc6)",
    "--color-syntax-type": "light-dark(#645a72, #b2a7c1)",
    "--color-syntax-variable": "light-dark(#5e5e5e, #ababb0)",
    "--color-syntax-operator": "light-dark(#5e5e5e, #ababb0)",
    "--color-syntax-constant": "light-dark(#755752, #bea792)",
    "--color-syntax-tag": "light-dark(#775751, #c7a39d)",
    "--color-syntax-attribute": "light-dark(#79693f, #b6aa90)",
    "--color-syntax-property": "light-dark(#4e6357, #94b2a0)",
    "--color-syntax-punctuation": "light-dark(#5e5e5e, #ababb0)",
    "--color-syntax-background": "light-dark(#f3f3f5, #171719)",
    "--color-accent": "#247768",
    "--color-accent-muted": "#e5f3ed",
    "--color-neutral": "light-dark(#25252a0f, #f3f3f51a)",
    "--color-background-surface": "light-dark(#ffffff, #1b1b1f)",
    "--color-background-body": "light-dark(#f3f3f5, #111015)",
    "--color-overlay": "light-dark(#25252a80, #28282acc)",
    "--color-overlay-hover": "light-dark(#25252a0d, #f3f3f50d)",
    "--color-overlay-pressed": "light-dark(#25252a1a, #f3f3f51a)",
    "--color-background-muted": "light-dark(#e2e2e8, #3b3b3f)",
    "--color-text-primary": "light-dark(#25252a, #f3f3f5)",
    "--color-text-secondary": "light-dark(#5e5e63, #ababb0)",
    "--color-text-disabled": "light-dark(#d7d7da, #5e5e61)",
    "--color-text-accent": "#247768",
    "--color-on-dark": "#FFFFFF",
    "--color-on-light": "light-dark(#25252a, #28282a)",
    "--color-on-accent": "#ffffff",
    "--color-on-success": "light-dark(#374c36, #d0e9ce)",
    "--color-on-error": "light-dark(#58413e, #f9dcd7)",
    "--color-on-warning": "light-dark(#524622, #f4e1b7)",
    "--color-icon-accent": "#247768",
    "--color-icon-primary": "light-dark(#25252a, #f3f3f5)",
    "--color-icon-secondary": "light-dark(#83838a, #9d9da3)",
    "--color-icon-disabled": "light-dark(#d7d7da, #5e5e61)",
    "--color-background-card": "light-dark(#FFFFFF, #242325)",
    "--color-background-popover": "light-dark(#ffffff, #25252a)",
    "--color-background-inverted": "light-dark(#25252a, #f3f3f5)",
    "--color-success": "light-dark(#374c36, #b4cdb2)",
    "--color-success-muted": "light-dark(#d0e9ce, #b4cdb2)",
    "--color-error": "light-dark(#58413e, #dcc0bc)",
    "--color-error-muted": "light-dark(#f9dcd7, #dcc0bc)",
    "--color-warning": "light-dark(#524622, #d7c59c)",
    "--color-warning-muted": "light-dark(#f4e1b7, #d7c59c)",
    "--color-border": "light-dark(#e2e2e8, #f3f3f51a)",
    "--color-border-emphasized": "light-dark(#83838a, #5e5e61)",
    "--color-skeleton": "light-dark(#d4d4da, #5e5e64)",
    "--color-shadow": "light-dark(#25252a1a, #0000004d)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#d7e4f5, #485362)",
    "--color-border-blue": "light-dark(#c9d6e7, #313c4a)",
    "--color-icon-blue": "light-dark(#3c4856, #d7e4f5)",
    "--color-text-blue": "light-dark(#3c4856, #d7e4f5)",
    "--color-background-cyan": "light-dark(#cce8e5, #3e5755)",
    "--color-border-cyan": "light-dark(#bedad7, #28403e)",
    "--color-icon-cyan": "light-dark(#334b49, #cce8e5)",
    "--color-text-cyan": "light-dark(#334b49, #cce8e5)",
    "--color-background-gray": "light-dark(#e2e2e8, #525257)",
    "--color-border-gray": "light-dark(#d4d4da, #3b3b3f)",
    "--color-icon-gray": "light-dark(#46464b, #e2e2e8)",
    "--color-text-gray": "light-dark(#46464b, #e2e2e8)",
    "--color-background-green": "light-dark(#d0e9ce, #425841)",
    "--color-border-green": "light-dark(#c2dbc0, #2b402b)",
    "--color-icon-green": "light-dark(#374c36, #d0e9ce)",
    "--color-text-green": "light-dark(#374c36, #d0e9ce)",
    "--color-background-orange": "light-dark(#ffdcbb, #684d32)",
    "--color-border-orange": "light-dark(#f1ceae, #4f361c)",
    "--color-icon-orange": "light-dark(#5b4227, #ffdcbb)",
    "--color-text-orange": "light-dark(#5b4227, #ffdcbb)",
    "--color-background-pink": "light-dark(#f0dde8, #5e4e57)",
    "--color-border-pink": "light-dark(#e2cfda, #463740)",
    "--color-icon-pink": "light-dark(#52424c, #f0dde8)",
    "--color-text-pink": "light-dark(#52424c, #f0dde8)",
    "--color-background-purple": "light-dark(#e8dff3, #564f60)",
    "--color-border-purple": "light-dark(#d9d1e5, #3f3949)",
    "--color-icon-purple": "light-dark(#4b4454, #e8dff3)",
    "--color-text-purple": "light-dark(#4b4454, #e8dff3)",
    "--color-background-red": "light-dark(#f9dcd7, #644d49)",
    "--color-border-red": "light-dark(#ebcec9, #4c3633)",
    "--color-icon-red": "light-dark(#58413e, #f9dcd7)",
    "--color-text-red": "light-dark(#58413e, #f9dcd7)",
    "--color-background-teal": "light-dark(#d4e7dc, #46564d)",
    "--color-border-teal": "light-dark(#c6d9ce, #303f36)",
    "--color-icon-teal": "light-dark(#3b4a41, #d4e7dc)",
    "--color-text-teal": "light-dark(#3b4a41, #d4e7dc)",
    "--color-background-yellow": "light-dark(#f4e1b7, #5e512d)",
    "--color-border-yellow": "light-dark(#e5d3a9, #463a18)",
    "--color-icon-yellow": "light-dark(#524622, #f4e1b7)",
    "--color-text-yellow": "light-dark(#524622, #f4e1b7)",
    "--radius-none": "0px",
    "--radius-inner": "0.25rem",
    "--radius-element": "0.5rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1.5rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 4px #28282A0D, 0 4px 8px #28282A1A",
    "--shadow-med": "0 2px 4px #28282A0D, 0 4px 12px #28282A1A",
    "--shadow-high": "0 4px 6px #28282A1A, 0 12px 24px #28282A26",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #28282A30",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #28282A50",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #83838a30",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #83838a30",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #83838a30"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)"
      },
      "variant:secondary": {
        "backgroundColor": "transparent",
        "borderWidth": "1.5px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)",
        ":hover": {
          "backgroundColor": "var(--color-neutral)"
        }
      },
      "variant:destructive": {
        "backgroundColor": "#c2252a",
        "color": "#ffffff",
        ":hover": {
          "backgroundColor": "color-mix(in srgb, #c2252a, var(--color-tint-hover) 15%)"
        },
        ":active": {
          "backgroundColor": "color-mix(in srgb, #c2252a, var(--color-tint-hover) 25%)"
        }
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:error": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      }
    },
    "banner": {
      "status:info": {
        "--color-accent-muted": "var(--color-background-blue)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "--color-success-muted": "var(--color-background-green)",
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-warning-muted": "var(--color-background-yellow)",
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-error-muted": "var(--color-background-red)",
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      }
    },
    "progress-bar-fill": {
      "variant:accent": {
        "backgroundColor": "light-dark(#d7e4f5, #a0acbc)"
      },
      "variant:success": {
        "backgroundColor": "light-dark(#d0e9ce, #9ab298)"
      },
      "variant:warning": {
        "backgroundColor": "light-dark(#f4e1b7, #bbaa82)"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#f9dcd7, #c0a5a0)"
      }
    },
    "progress-bar-track": {
      "base": {
        "backgroundColor": "var(--color-skeleton)"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--color-skeleton)"
      }
    },
    "field-status": {
      "type:success": {
        "backgroundColor": "var(--color-background-green)"
      },
      "type:warning": {
        "backgroundColor": "var(--color-background-yellow)"
      },
      "type:error": {
        "backgroundColor": "var(--color-background-red)"
      }
    },
    "text-input": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "text-area": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "number-input": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "date-input": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "time-input": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "selector": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "multi-selector": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "typeahead": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "tokenizer": {
      "status:success": {
        "--color-success": "light-dark(#7f977e, #99b298)"
      },
      "status:warning": {
        "--color-warning": "light-dark(#9f8f68, #bbaa81)"
      },
      "status:error": {
        "--color-error": "light-dark(#a58b86, #c0a5a1)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "toast": {
      "type:success": {
        "backgroundColor": "var(--color-success)",
        "color": "var(--color-on-success)"
      }
    },
    "table-scroll-wrapper": {
      "base": {
        "height": "100%",
        "scrollbarGutter": "stable"
      }
    },
    "table-header": {
      "base": {
        "backgroundColor": "#dceee8"
      }
    },
    "table-header-cell": {
      "base": {
        "backgroundColor": "#dceee8",
        "color": "#18594e",
        "position": "sticky",
        "top": "0",
        "zIndex": "2"
      }
    },
    "table-body": {
      "base": {
        "backgroundColor": "var(--color-background-card)"
      }
    },
    "table-footer": {
      "base": {
        "backgroundColor": "var(--color-background-muted)"
      }
    },
    "tab": {
      "selected": {
        "backgroundColor": "var(--color-accent-muted)",
        "color": "var(--color-text-accent)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 14,
        "ratio": 1.25
      },
      "body": {
        "family": "Figtree",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif"
      },
      "heading": {
        "family": "Montserrat",
        "fallbacks": "\"Figtree\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
        "weights": {
          "3": "bold",
          "4": "bold"
        }
      },
      "code": {
        "family": "JetBrains Mono",
        "fallbacks": "\"SF Mono\", Monaco, Consolas, monospace"
      }
    },
    "motion": {
      "fast": 125,
      "medium": 300,
      "slow": 700,
      "ratio": 0.75
    }
  },

};
