/**
 * "Maritime" custom component folder (user request, 2026-09-18) — a
 * design system supplied as `.stitch/DESIGN.md`, mapped onto a custom
 * Astryx theme (`theme.js`) plus domain components rebuilt from the
 * Stitch mockup (`contract-overview-card.jsx`). Not wired into any page
 * yet: wrap the subtree that should use it in `MaritimeThemeProvider`,
 * then use these components inside.
 *
 * @example
 * import {
 *   MaritimeThemeProvider,
 *   MaritimeContractOverviewCard,
 * } from '@/shared/components/custom/maritime/index.js';
 *
 * <MaritimeThemeProvider>
 *   <MaritimeContractOverviewCard
 *     contractCode="CT-2024/EXP-088"
 *     projectName="Metro Line 2 (Bến Thành - Tham Lương)"
 *     typeLabel="Chính thức"
 *     statusLabel="Đang thực hiện"
 *     incotermLabel="CIF 2020"
 *     actionItems={[]}
 *   />
 * </MaritimeThemeProvider>
 */
export { MaritimeAnnexListPanel } from './annex-list-panel.jsx';
export { MaritimeBadge } from './badge.jsx';
export { MaritimeButton } from './button.jsx';
export { MaritimeCard } from './card.jsx';
export { MaritimeChip } from './chip.jsx';
export { MaritimeCommissionPanel } from './commission-panel.jsx';
export { MaritimeContractCodeTextInput } from './contract-code-text-input.jsx';
export { MaritimeContractFoundationGrid } from './contract-foundation-grid.jsx';
export { MaritimeContractOverviewCard } from './contract-overview-card.jsx';
export { MaritimeDateInput } from './date-input.jsx';
export { MaritimeDateTimeInput } from './date-time-input.jsx';
export { MaritimeFormSection } from './form-section.jsx';
export { MaritimeNumberInput } from './number-input.jsx';
export { MaritimePaymentProgressPanel } from './payment-progress-panel.jsx';
export { MaritimePaymentSummaryCard } from './payment-summary-card.jsx';
export { MaritimePaymentTermCard } from './payment-term-card.jsx';
export { MaritimeSelector } from './selector.jsx';
export { MaritimeShipmentListPanel } from './shipment-list-panel.jsx';
export { MaritimeTabNav } from './tab-nav.jsx';
export { MaritimeThemeProvider } from './theme-provider.jsx';
// The *built* theme (`maritime.js`, generated by `astryx theme build
// theme.js`), not the raw `theme.js` source — this is the same object
// `MaritimeThemeProvider` applies, so re-exporting the source here would
// let two different theme objects with the same name float around.
export { maritimeTheme } from './maritime.js';
