/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\maritime\theme.js
 * Command: astryx theme build src\shared\components\custom\maritime\theme.js --out src\shared\components\custom\maritime\theme.built.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'maritime-muted': true;
    'maritime-subtle': true;
    'maritime-teal': true;
    'maritime-teal-text': true;
  }
}

declare module '@astryxdesign/core/Token' {
  interface TokenColorMap {
    'maritime': true;
  }
}
