/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\maritime\theme.js
 * Command: astryx theme build src\shared\components\custom\maritime\theme.js --out src\shared\components\custom\maritime\theme.built.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./maritime.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const maritimeTheme: DefinedTheme;
