/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\maritime\theme.js
 * Command: astryx theme build src\shared\components\custom\maritime\theme.js --out src\shared\components\custom\maritime\theme.built.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/**
 * maritime theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { maritimeTheme } from './maritime';
 *   import './maritime.css';
 */
export const maritimeTheme = {
  name: 'maritime',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#0E53D8, #C2C0FF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #00298A)",
    "--color-neutral": "light-dark(#1B1B221A, #E2E1EB33)",
    "--color-background-surface": "#ffffff",
    "--color-background-body": "#f8f9ff",
    "--color-overlay": "light-dark(#1B1B2266, #1B1B2299)",
    "--color-overlay-hover": "light-dark(#1B1B220D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B221A, #FFFFFF1A)",
    "--color-background-muted": "transparent",
    "--color-text-primary": "#0b1c30",
    "--color-text-secondary": "#475569",
    "--color-text-disabled": "light-dark(#908F9D, #5E5D6A)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "#0b1c30",
    "--color-icon-secondary": "#475569",
    "--color-icon-disabled": "light-dark(#908F9D, #5E5D6A)",
    "--color-background-card": "#ffffff",
    "--color-background-popover": "#e5eeff",
    "--color-background-inverted": "light-dark(#1B1B22, #FCFCFF)",
    "--color-border": "#dce9ff",
    "--color-border-emphasized": "#cbd5e1",
    "--color-skeleton": "light-dark(#ABAAB8, #464552)",
    "--color-track": "light-dark(#ABAAB8, #464552)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "28px",
    "--radius-chat": "28px",
    "--radius-full": "9999px",
    "--font-family-body": "\"Optimistic Text Vietnamese\", \"Optimistic Text\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "\"Optimistic Text Vietnamese\", \"Optimistic Text\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "\"Optimistic Text Vietnamese\", \"Optimistic Text\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--color-error": "#b91c1c",
    "--color-on-error": "#ffffff",
    "--color-error-muted": "#fee2e2",
    "--color-success": "#0d9488",
    "--color-on-success": "#ffffff",
    "--color-success-muted": "#f0fdfa",
    "--maritime-text-muted": "#0B1C30",
    "--maritime-text-subtle": "#45464d",
    "--maritime-teal-value": "#0f766e",
    "--maritime-teal-text": "#115e59",
    "--maritime-teal-border": "#99f6e4",
    "--maritime-step-active-bg": "#eff6ff",
    "--maritime-badge-teal-bg": "#ccfbf1",
    "--maritime-button-primary-hover": "#1d4ed8",
    "--maritime-button-secondary-hover": "#e5eeff",
    "--maritime-badge-info-bg": "rgba(239, 246, 255, 0.5)",
    "--maritime-badge-info-border": "#bfdbfe",
    "--maritime-badge-info-text": "#0051d5",
    "--maritime-badge-success-bg": "#ecfdf5",
    "--maritime-badge-success-border": "#a7f3d0",
    "--maritime-badge-success-text": "#065f46",
    "--maritime-badge-success-dot": "#0d9488",
    "--maritime-badge-warning-bg": "#fffbeb",
    "--maritime-badge-warning-border": "#fde68a",
    "--maritime-badge-warning-text": "#92400e",
    "--maritime-badge-error-bg": "#fee2e2",
    "--maritime-badge-error-border": "#fecaca",
    "--maritime-badge-error-text": "#7f1d1d",
    "--maritime-badge-neutral-bg": "#eff4ff",
    "--maritime-badge-neutral-border": "#cbd5e1",
    "--maritime-badge-neutral-text": "#475569",
    "--maritime-chip-bg": "#dbe1ff",
    "--maritime-chip-text": "#00174b",
    "--maritime-chip-border": "#bfdbfe",
    "--maritime-tab-border": "rgba(220, 233, 255, 0.6)",
    "--maritime-tab-resting-bg": "var(--color-background-surface)",
    "--maritime-contract-code-font": "\"JetBrains Mono\", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "--maritime-field-label-color": "#45464d"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "20px",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)",
        "letterSpacing": "-0.5px"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "color:maritime-muted": {
        "color": "var(--maritime-text-muted)"
      },
      "color:maritime-subtle": {
        "color": "var(--maritime-text-subtle)"
      },
      "color:maritime-teal": {
        "color": "var(--maritime-teal-value)"
      },
      "color:maritime-teal-text": {
        "color": "var(--maritime-teal-text)"
      }
    },
    "field-label": {
      "base": {
        "--text-supporting-size": "11px",
        "--text-supporting-leading": "16.5px",
        "color": "var(--maritime-field-label-color)",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-semibold)",
        "lineHeight": "16.5px"
      }
    },
    "text-input": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)",
        "paddingBlock": "7px",
        "paddingInline": "10px"
      },
      "size:md": {
        "height": "32px"
      }
    },
    "selector": {
      "base": {
        "--text-label-size": "12px",
        "--text-label-leading": "18px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)",
        "paddingInline": "10px"
      },
      "size:md": {
        "minHeight": "36px",
        "paddingBlock": "6px"
      }
    },
    "date-input": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)",
        "paddingBlock": "7px",
        "paddingInline": "10px"
      },
      "size:md": {
        "height": "32px"
      }
    },
    "date-time-input": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)"
      }
    },
    "time-input": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)"
      }
    },
    "number-input": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)",
        "paddingBlock": "7px",
        "paddingInline": "10px"
      },
      "size:md": {
        "height": "32px"
      }
    },
    "input-group": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "16px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)"
      },
      "size:md": {
        "height": "32px"
      }
    },
    "textarea": {
      "base": {
        "--text-body-size": "12px",
        "--text-body-leading": "19.5px",
        "backgroundColor": "var(--color-background-surface)",
        "borderColor": "var(--color-border)",
        "borderRadius": "calc(var(--radius-inner) / 2)",
        "paddingInline": "10px"
      },
      "size:md": {
        "height": "80.5px"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-inner)",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "var(--radius-inner)",
        "fontSize": "16px",
        "lineHeight": "22px",
        "paddingBlock": "2px"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-inner)",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border)",
        "boxShadow": "0 1px 2px 0 rgba(15, 23, 42, 0.04)"
      }
    },
    "icon": {
      "color:maritime-muted": {
        "color": "var(--maritime-text-muted)"
      },
      "color:maritime-subtle": {
        "color": "var(--maritime-text-subtle)"
      },
      "color:maritime-teal": {
        "color": "var(--maritime-teal-value)"
      },
      "color:maritime-teal-text": {
        "color": "var(--maritime-teal-text)"
      }
    },
    "table-header": {
      "base": {
        "backgroundColor": "var(--color-background-muted)"
      }
    },
    "table-header-cell": {
      "base": {
        "color": "var(--maritime-text-muted)",
        "fontSize": "13px",
        "fontWeight": "700",
        "letterSpacing": "0.05em",
        "textTransform": "uppercase"
      }
    },
    "table-cell": {
      "base": {
        "fontSize": "var(--font-size-base)",
        "lineHeight": "22px"
      }
    },
    "token": {
      "base": {
        "fontSize": "16px",
        "lineHeight": "24px"
      },
      "color:maritime": {
        "backgroundColor": "var(--maritime-chip-bg)",
        "borderColor": "var(--maritime-chip-border)",
        "color": "var(--maritime-chip-text)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
