/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\meta\theme.js
 * Command: astryx theme build src\shared\components\custom\meta\theme.js --out src\shared\components\custom\meta\theme.built.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./meta.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const metaTheme: DefinedTheme;
