/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\meta\theme.js
 * Command: astryx theme build src\shared\components\custom\meta\theme.js --out src\shared\components\custom\meta\theme.built.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Text' {
  interface TextColorMap {
    'meta-success': true;
    'meta-success-deep': true;
    'meta-subtle': true;
    'meta-amber': true;
    'meta-green': true;
  }
}
