/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\shared\components\custom\ibm-plex-corporate\theme.js
 * Command: astryx theme build src\shared\components\custom\ibm-plex-corporate\theme.js --out src\shared\components\custom\ibm-plex-corporate\theme.built.css
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const ibmPlexCorporateTheme: DefinedTheme;
