/**
 * "IBM Plex Corporate" custom component folder (user request, 2026-09-17)
 * — a design system supplied as a color/typography/shape spec, mapped
 * onto a custom Astryx theme (`theme.js`) plus a handful of thin
 * component wrappers with the spec's own sensible defaults. Not wired
 * into any page yet: wrap the subtree that should use it in
 * `IbmPlexCorporateThemeProvider`, then use these components inside.
 *
 * @example
 * import {
 *   IbmPlexCorporateThemeProvider,
 *   IbmPlexButton,
 *   IbmPlexCard,
 * } from '@/shared/components/custom/ibm-plex-corporate/index.js';
 *
 * <IbmPlexCorporateThemeProvider>
 *   <IbmPlexCard>
 *     <IbmPlexButton label="Lưu" />
 *   </IbmPlexCard>
 * </IbmPlexCorporateThemeProvider>
 */
export { IbmPlexCorporateThemeProvider } from './theme-provider.jsx';
// The *built* theme (`ibm-plex-corporate.js`, generated by `astryx theme
// build theme.js`), not the raw `theme.js` source — this is the same
// object `IbmPlexCorporateThemeProvider` applies, so re-exporting the
// source here would let two different theme objects with the same name
// float around.
export { IbmPlexButton } from './button.jsx';
export { IbmPlexCard } from './card.jsx';
export { IbmPlexCheckboxInput } from './checkbox.jsx';
export { IbmPlexChip } from './chip.jsx';
export { ibmPlexCorporateTheme } from './ibm-plex-corporate.js';
export { IbmPlexTextInput } from './input.jsx';
export { IbmPlexList, IbmPlexListItem } from './list.jsx';
